// swift-tools-version: 5.9
// Generated by scripts/release.sh for MolocoEventsSDK 0.1.0 — do not edit by hand.
import PackageDescription

let package = Package(
    name: "MolocoEventsSDK",
    platforms: [.iOS(.v12)],
    products: [
        .library(name: "MolocoEventsSDK", targets: ["MolocoEventsSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "MolocoEventsSDK",
            url: "https://moloco-ios-build.s3.amazonaws.com/events-sdk/0.1.0/MolocoEventsSDK-0.1.0.xcframework.zip",
            checksum: "654f2b6dba6e4506d7c517c09b343d03052dde228c2b188e83659365bf836601"
        ),
    ]
)
