// swift-tools-version: 5.9
// Generated by scripts/release.sh for MolocoEventsSDK 0.1.1 — do not edit by hand.
import PackageDescription

let package = Package(
    name: "MolocoEventsSDK",
    platforms: [.iOS(.v12)],
    products: [
        .library(name: "MolocoEventsSDK", targets: ["MolocoEventsSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "MolocoEventsSDK",
            url: "https://moloco-ios-build.s3.amazonaws.com/events-sdk/0.1.1/6410da291304c7d26579e904596017ad79858a642e9baca72d5c76cccc7b9112/MolocoEventsSDK-0.1.1.xcframework.zip",
            checksum: "6410da291304c7d26579e904596017ad79858a642e9baca72d5c76cccc7b9112"
        ),
    ]
)
