// swift-tools-version: 5.9
// Generated by scripts/release.sh for MolocoEventsSDK 0.1.0 — do not edit by hand.
import PackageDescription

let package = Package(
    name: "MolocoEventsSDK",
    platforms: [.iOS(.v12)],
    products: [
        .library(name: "MolocoEventsSDK", targets: ["MolocoEventsSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "MolocoEventsSDK",
            url: "https://moloco-ios-build.s3.amazonaws.com/events-sdk/0.1.0/82b39bb7b49f15485b8e4713fb25bef25afa8fc6c411a8c40cf116ab0bed8f2b/MolocoEventsSDK-0.1.0.xcframework.zip",
            checksum: "82b39bb7b49f15485b8e4713fb25bef25afa8fc6c411a8c40cf116ab0bed8f2b"
        ),
    ]
)
